---
name: Build

"on":
  push:
    branches:
      - "**"
    tags:
      - "**"

permissions:
  actions: read
  checks: write
  contents: write
  id-token: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace
      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > keystore.jks
      - name: List Build Tools
        run: ls "$ANDROID_HOME"/build-tools/

      - name: Zipalign APK
        run: |
          "$ANDROID_HOME"/build-tools/34.0.0/zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            PlayPause-aligned.apk
      - name: Sign APK
        run: |
          "$ANDROID_HOME"/build-tools/34.0.0/apksigner sign --ks keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --out "PlayPause-${{ github.ref_name }}.apk" \
            PlayPause-aligned.apk
      - name: Verify signature
        run: |
          "$ANDROID_HOME"/build-tools/34.0.0/apksigner verify --verbose "PlayPause-${{ github.ref_name }}.apk"
      - name: Upload Artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: "PlayPause-${{ github.ref_name }}"
          path: "PlayPause-${{ github.ref_name }}.apk"
      - name: Release APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref }}
          files: "PlayPause-${{ github.ref_name }}.apk"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
