name: Build and Release

on: #[push]
  milestone: # TODO: remove placeholder
    types: [opened, deleted]

permissions:
  actions: read
  checks: write
  contents: write
  id-token: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
